### ISSUE TITLE
Ergänzungsvorschläge Abkürzungsverzeichnis

### ISSUE THREAD

**Issue by THK-IB** [waltraud-int/MALIS-20.3-WPM_T9_Sara_Melchior#2]
@waltraud-int: Die könnten noch im Abkürzungsverzeichnis aufgenommen werden:

- **CSV**: Comma-separated-values

- **DH**: Digital Humanities

- **SuUB Bremen**: Staats- und Universitätsbibliothek Bremen

**Comment by waltraud-int** [comment]
@THK-IB 
Danke! Habe ich direkt so übernommen.
