### ISSUE TITLE
Händische Suche in OCR-Scans

### ISSUE THREAD

**Issue by THK-IB** [waltraud-int/MALIS-20.3-WPM_T9_Sara_Melchior#4]
@waltraud-int:

"_Die OCR-Scans müssen derzeit **händisch** nach Begriffen durchsucht werden, damit Tags vergeben werden können._"

Mich irritiert das Bild, dass OCR-Scans händisch durchsucht werden, weil sie doch auf Servern oder Festplatten liegen. Nun stelle ich mir vor, wie Mitarbeiter:innen Festplatte für Festplatte, CD für CD, Diskette für Diskette usw. in die Hände nehmen, gegen das Licht halten und prüfend begutachten... Vielleicht lieber manuell? Bedeutet das gleiche, ist aber nicht so bildstark.

**Comment by waltraud-int** [comment]
@THK-IB 
Ja- du hast natürlich recht. :D Manuell klingt besser.
